[font]
size = 18

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Medium"

[window]
startup_mode = "Windowed" #'Windowed' 'Maximized' 'Fullscreen' 'SimpleFullscreen'
decorations = "none"
dynamic_title = true

[window.padding]
x = 0
y = 0

[general]
import = [
  "./catppuccin-mocha.toml"
]

[terminal]

[terminal.shell]
program = "wsl"
