console_title_template = '{{if .Root}}(Admin){{end}} {{.PWD}}'
version = 4

[transient_prompt]
template = '❯ '
foreground = '#a6e3a1'
type = 'text'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }} #f38ba8 {{ end }}']

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
template = ' {{.UserName}} '
foreground = '#f9e2af'
type = 'session'
style = 'plain'

[[blocks.segments]]
template = ' {{.Path}} '
foreground = '#89dceb'
type = 'path'
style = 'plain'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = "git"
style = "plain"
foreground = "#89b4fa"
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }} #89b4fa {{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }} #89b4fa {{ end }}",
  "{{ if gt .Ahead 0 }} #89b4fa {{ end }}",
  "{{ if gt .Behind 0 }} #89b4fa {{ end }}",
]
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .Ahead 0 }}  {{ .Ahead }}{{ end }}{{ if gt .Behind 0 }}  {{ .Behind }}{{ end }} "

[blocks.segments.properties]
fetch_status = true
fetch_upstream_icon = true
source = "cli"

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
template = ' {{ .FormattedMs }} '
foreground = '#A3BE8C'
type = 'executiontime'
style = 'plain'

[[blocks]]
type = 'prompt'
alignment = 'right'
overflow = 'hide'

[[blocks.segments]]
type = "go"
style = "plain"
foreground = "#ffffff"
background = "#00ADD8"
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
fetch_version = true
parse_mod_file = true
display_mode = "files"

[[blocks.segments]]
type = "bun"
style = "plain"
foreground = "#1e293b"
background = "#fbf0df"
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
fetch_version = true
missing_command_text = "N/A"
display_mode = "files"

[[blocks.segments]]
type = "rust"
style = "plain"
foreground = "#ffffff"
background = "#b7410e"
template = "  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
fetch_version = true
display_mode = "files"

[[blocks.segments]]
foreground = "#89b4fa"
type = 'os'
style = 'plain'

[[blocks.segments]]
template = '  {{ .Name }}'
foreground = '#f9e2af'
type = 'shell'
style = 'plain'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '❯ '
foreground = '#a6e3a1'
type = 'text'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }} #BF616A {{ end }}']
